version: "3.9"

volumes:
  ai_system:

services:
  learning:
    image: shashankk5/event-based-market-learning:latest
    volumes:
      - ai_system:/tmp

  knowledge:
    image: shashankk5/event-based-market-knowledge:latest
    volumes:
      - ai_system:/tmp

  activation:
    image: shashankk5/event-based-market-activation:latest
    volumes:
      - ai_system:/tmp

  code:
    image: shashankk5/event-based-market-code:latest
    volumes:
      - ai_system:/tmp
